### ISSUE TITLE
Adding attachments 

### ISSUE THREAD

**Issue by srinatha** [LTe/acts-as-messageable#36]
Hi,

Is there a way to add attachments to conversation  while sending  replies  similar to facebook ?

**Comment by mices** [comment]
Where does acts_as_messagable store conversations and messages?

**Comment by mices** [comment]
if i create a message model, messages table with an attachment field (string) and a custom class in which class do i mount an uploader for the field attachment, CustomMessage or Message?

**Comment by mices** [comment]
acts_as_messageable :class_name => "CustomMessage"

That syntax raises an error
