### ISSUE TITLE
Scope: Search conflicting with Ransack/Active Admin in Rails 4.1.1

### ISSUE THREAD

**Issue by michaelschmitz** [LTe/acts-as-messageable#62]
Hi,
thanks for the work on the gem.

After updating to Rails 4.1.1, I get the following error:

```
c:/Ruby2/lib/ruby/gems/2.0.0/gems/activerecord-   4.1.1/lib/active_record/scoping/named.rb:143:in `scope': You tried to define a scope  named "search" on the model "ActsAsMessageable::Message", but Active Record already defined a class method with the same name. (ArgumentError)
```

This is due to me having installed Active Admin, which requires Ransack. Ransack also defines :search as an alias to :ransack (see here: https://github.com/activerecord-hackery/ransack/issues/369). I've taken efforts to change all of my own :search scopes, but now I have to find a way to either change ransack's or messageable's scope to avoid this error.

My understanding of how to do this is currently limited, the advice in the link above regarding "remove_class" only leads to other, cascading problems. Is it possible to change the name of the scope or to have an initializer setting that renames the method?

I assume quite a few people use the "search" scope, I don't require it.

**Comment by CV-Gate** [comment]
+1

**Comment by LTe** [comment]
I think name of `search` scope should be configurable. I'm open for pull requests.

**Comment by danielpclark** [comment]
+1

**Comment by Envek** [comment]
Thinking Sphinx is adding `search` scope to models too.

Solution from #73 by @danielpclark helps. Thanks!

**Comment by LTe** [comment]
Closed by https://github.com/LTe/acts-as-messageable/pull/96
