### ISSUE TITLE
Multiple messageables in one app?

### ISSUE THREAD

**Issue by ok11** [LTe/acts-as-messageable#63]
I created two Messageables: "User" and "The Wall". The first one is for normal messages (Message model), the second one is for wall records (WallRecord model, no topic, shorter body). I'm trying to store them in one table (messages as per default)
But when I send messages (which should create instances of Message model), they are created as wall records. If I log them in the debug log, they are logged as #<WallRecord id:1 ... >
Is it possible at all to have more than one messageable in an app?

**Comment by LTe** [comment]
I think it is possible. But when you define custom class (https://github.com/LTe/acts-as-messageable#custom-class) this object will create `CustomClass` objects. Can you provide code examples?
