### ISSUE TITLE
Message class inheritance

### ISSUE THREAD

**Issue by mbanduk** [LTe/acts-as-messageable#68]
Hi @LTe,

How should I do if I need Inheritance for the custom message class?!

**Comment by LTe** [comment]
What do you mean? You can create your own custom class.

https://github.com/LTe/acts-as-messageable#custom-class

**Comment by mbanduk** [comment]
Sure,

Thats what I did, I was just having some problems because of my inexperience on ruby.

Thank you @LTe!
