### ISSUE TITLE
Can't mass-assign protected attributes: body, topic

### ISSUE THREAD

**Issue by yashwinkumar** [LTe/acts-as-messageable#76]
[34] pry(main)> u2.send_message(u, { :body => "Hash body", :topic => "Hash topic" })
ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes: body, topic
from /home/ashwin/.rvm/gems/ruby-1.9.3-p545/gems/activemodel-3.2.8/lib/active_model/mass_assignment_security/sanitizer.rb:48:in `process_removed_attributes'

User.rb
  acts_as_messageable :dependent  => :destroy, :group_messages => true 

I installed version 0.4.10
How can I fix this.

**Comment by vinnybod** [comment]
I was able to solve this issue with:

https://github.com/LTe/acts-as-messageable/issues/57

gem 'acts-as-messageable', :git => 'git://github.com/hocza/acts-as-messageable.git'

**Comment by LTe** [comment]
Fixed with https://github.com/LTe/acts-as-messageable/pull/94
