### ISSUE TITLE
Warning persists on last version with Rails 3.2.15

### ISSUE THREAD

**Issue by valinaga** [LTe/acts-as-messageable#82]
Hi,

I reopened this issue posted in the past. Keep getting these warnings at each instance of User acting as messageable.

Creating scope :are_from. Overwriting existing method ActsAsMessageable::Message.are_from.
Creating scope :are_to. Overwriting existing method ActsAsMessageable::Message.are_to.
Creating scope :search. Overwriting existing method ActsAsMessageable::Message.search.
Creating scope :connected_with. Overwriting existing method ActsAsMessageable::Message.connected_with.
Creating scope :readed. Overwriting existing method ActsAsMessageable::Message.readed.
Creating scope :unreaded. Overwriting existing method ActsAsMessageable::Message.unreaded.
Creating scope :deleted. Overwriting existing method ActsAsMessageable::Message.deleted.

Is there a way to get rid of these?
Thanks

**Comment by LTe** [comment]
Closed by https://github.com/LTe/acts-as-messageable/pull/96
