### ISSUE TITLE
ActiveAdmin + ActsAsMessageable

### ISSUE THREAD

**Issue by kedarnag138** [LTe/acts-as-messageable#84]
I am facing trouble when I use this gem. I am getting an unusual error, which I have not been able to solve. I am attaching the screenshot of the error. Please, I need help.
![screen shot 2017-02-03 at 21 27 49](https://cloud.githubusercontent.com/assets/5475397/22601469/0222d276-ea65-11e6-9f85-0d20aec4fe74.png)

**Comment by ken-wong** [comment]
this pull request maybe help [#73](https://github.com/LTe/acts-as-messageable/pull/73)

**Comment by LTe** [comment]
Closed by https://github.com/LTe/acts-as-messageable/pull/96
